
# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ./src/ ./public/"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings.
[context.production]
  command = "npm run build"
  publish = "dist"

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data: *; img-src 'self' data: https:; connect-src 'self' https://fhyhyfoqzpkzkxbkqcdp.supabase.co wss://fhyhyfoqzpkzkxbkqcdp.supabase.co;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Set aggressive cache control headers for faster loading
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable Brotli and Gzip compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Enable SPA routing - this is critical for Vercel and Netlify deployments
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure for high traffic
[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

# Add environment variables
[context.production.environment]
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"

# Add build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

