
# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings.
[context.production]
  command = "npm run build"
  publish = "dist"

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://fhyhyfoqzpkzkxbkqcdp.supabase.co;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Set cache control headers for faster loading
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure for high traffic
[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
